UPDATE HZGraph SET tJpShin='二' WHERE tHanzi='二';
UPDATE HZGraph SET tJpShin='十' WHERE tHanzi='十';
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi1','it',32747,1,NULL,NULL,NULL,NULL,NULL,'yi2 yi4','弌','壹',NULL,NULL,NULL,'第一','单用或词尾念阴平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi2','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一半','去声前念阳平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi4','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一点','阴平、阳平、上声前念去声');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='ding1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding1','dieng',16,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉 疔 叮 盯',NULL,'打',NULL,'壮丁',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding4','diengh',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉',NULL,NULL,NULL,'密丁','汉语大词典');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='zheng1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','zheng1','dyaeng',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'丁丁',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','ya4','eat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'乚',NULL,'轧',NULL,'乙乙','古代汉语大词典读ya4');
DELETE FROM HZMorph WHERE tHZ='乙' AND tPY='yi3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','it',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'虚拟广韵读音');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','iut',45,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'甲乙 乙等','粤语读圆唇(通字S18-6)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','ic',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'意','忆',NULL,NULL,'意古音-ks');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','it',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠃉',NULL,'鳦',NULL,'非凫则乙','乙鸟燕也');
DELETE FROM HZMorph WHERE tHZ='二' AND tPY='er4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('二','er4','erh',2718,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'弍','贰',NULL,'次',NULL,'二流','据官话吴语日止ri作er(通字S7-8); 次,说文二声,子音七,古snh-');
DELETE FROM HZMorph WHERE tHZ='十' AND tPY='shi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('十','shi2','zhip',4082,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'拾 什',NULL,NULL,NULL,'十分',NULL);
