DROP TRIGGER HZGDefaults;
DROP TRIGGER HZGParChkIns;
DROP TRIGGER HZGParChk;
DROP TRIGGER HZGHzChk;
DROP TRIGGER HZGParChkDel;
DROP TRIGGER HZMPhChkIns;
DROP TRIGGER HZMPhChk;
DROP TRIGGER HZMHzChk;
DROP TRIGGER HZMPyChk;
DROP TRIGGER HZMMgcrChk;
DROP TRIGGER HZMPhChkDel;
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('㫃',NULL,'㫃','方人','㫃','方入','㫃','方人');
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('丂',NULL,'丂','考','丂','考','丂','丂');
UPDATE HZGraph SET tJpShin='下' WHERE tHanzi='下';
UPDATE HZGraph SET tTrad='乃 迺 廼', tJpShin='乃' WHERE tHanzi='乃';
UPDATE HZGraph SET tSimp='干 乾', tJpShin='乾 干' WHERE tHanzi='乾';
UPDATE HZGraph SET tTrad='了 瞭' WHERE tHanzi='了';
UPDATE HZGraph SET tJpShin='二' WHERE tHanzi='二';
UPDATE HZGraph SET tTrad='於 于', tJpShin='於 于' WHERE tHanzi='于';
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('倝',NULL,'倝','乾','倝','幹','倝','倝');
UPDATE HZGraph SET tJpShin='児' WHERE tHanzi='儿';
UPDATE HZGraph SET tJpShin='児' WHERE tHanzi='兒';
UPDATE HZGraph SET tTrad='幾 几', tJpShin='幾 机 几' WHERE tHanzi='几';
UPDATE HZGraph SET tJpShin='刀' WHERE tHanzi='刀';
UPDATE HZGraph SET tJpShin='十' WHERE tHanzi='十';
UPDATE HZGraph SET tTrad='卜 蔔', tJpShin='卜 蔔' WHERE tHanzi='卜';
UPDATE HZGraph SET tTrad='廠 厂', tJpShin='厰 厂' WHERE tHanzi='厂';
UPDATE HZGraph SET tGBFB='假', tB5FB='假' WHERE tHanzi='叚';
UPDATE HZGraph SET tJpShin='嚇' WHERE tHanzi='吓';
UPDATE HZGraph SET tTrad='幹 乾 干', tJpShin='幹 干 乾' WHERE tHanzi='干';
UPDATE HZGraph SET tTrad='才 纔', tJpShin='才 纔' WHERE tHanzi='才';
UPDATE HZGraph SET tSimp='干', tGBFB='干', tJpShin='幹 槏' WHERE tHanzi='榦';
UPDATE HZGraph SET tGBFB='谗' WHERE tHanzi='毚';
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('畐',NULL,'畐','匐','畐','匐','畐','畐');
UPDATE HZGraph SET tSimp='才', tGBFB='才' WHERE tHanzi='纔';
UPDATE HZGraph SET tJpShin='与' WHERE tHanzi='與';
UPDATE HZGraph SET tSimp='卜', tGBFB='卜', tJpShin='蔔' WHERE tHanzi='蔔';
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('虍',NULL,'虍','虍','虍','虍','虍','虍');
UPDATE HZGraph SET tSimp='乃 迺', tGBFB='乃', tJpShin='乃 迺' WHERE tHanzi='迺';
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('雐',NULL,'雐','虍','雐','虍','雐','虍');
UPDATE HZGraph SET tGBFB='倪', tTrad='齯', tB5FB='齯', tJpShin='齯', tJISFB='齯' WHERE tHanzi='𫠜';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('㫃','yan3','yenx',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'旌旗之游㫃蹇之貌','读若偃(说文)。通字S16无ienx,影改以');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi1','it',32747,1,NULL,NULL,NULL,NULL,NULL,'yi2 yi4','弌','壹',NULL,NULL,NULL,'第一','单用或词尾念阴平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi2','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一半','去声前念阳平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi4','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一点','阴平、阳平、上声前念去声');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='ding1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding1','dieng',16,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉 疔 叮 盯',NULL,'打',NULL,'壮丁',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding4','diengh',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉',NULL,NULL,NULL,'密丁','汉语大词典');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='zheng1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','zheng1','draeng',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'丁丁','通字S21无dyaeng,知改庄');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丂','kao3','kaux',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'考','于 亐',NULL,NULL,NULL,NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丂','qiao3','keaux',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'巧',NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='七' AND tPY='qi1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('七','qi1','tsit',950,1,NULL,NULL,NULL,NULL,NULL,'qi2',NULL,'柒 漆 桼',NULL,NULL,NULL,'七夕',NULL);
DELETE FROM HZMorph WHERE tHZ='七' AND tPY='qi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('七','qi2','tsit',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'七月','在去声字前念阳平(现汉),今非');
DELETE FROM HZMorph WHERE tHZ='丈' AND tPY='zhang4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丈','zhang4','dhyangx',112,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'杖',NULL,'丈量 丈夫',NULL);
DELETE FROM HZMorph WHERE tHZ='三' AND tPY='san1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('三','san1','sam',3030,1,NULL,NULL,NULL,NULL,NULL,NULL,'弎','叁 参',NULL,'参',NULL,'三才',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('三','san4','sam',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'三思','旧读,今非。广韵去声。通字S11无samh改平声');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('下','jia3','ceax',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'假','叚',NULL,NULL,'下借','汉语大词典作去声,非。简体可作叚省,虾声旁');
DELETE FROM HZMorph WHERE tHZ='下' AND tPY='xia4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('下','xia4','heah',6430,1,NULL,NULL,NULL,NULL,'ha4',NULL,'丅',NULL,NULL,'落',NULL,'在下 低下 一下子','对上之下古读上声,音夏,今并入去声');
DELETE FROM HZMorph WHERE tHZ='下' AND tPY='xia5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('下','xia5','heah',249,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'底下(129) 地下(56) 乡下(64)','轻声(现汉)。XDHYPLCD 8548词表第1208,2512,2666条(pp515,540,543)');
DELETE FROM HZMorph WHERE tHZ='与' AND tPY='yu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('与','yu2','yu',1,0,NULL,NULL,NULL,NULL,NULL,NULL,'與','欤',NULL,'邪',NULL,NULL,'语助');
DELETE FROM HZMorph WHERE tHZ='与' AND tPY='yu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('与','yu3','yux',962,1,NULL,NULL,NULL,NULL,NULL,NULL,'與','举 予',NULL,'舍',NULL,'赠与 与共',NULL);
DELETE FROM HZMorph WHERE tHZ='与' AND tPY='yu4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('与','yu4','yuh',10,0,NULL,NULL,NULL,NULL,NULL,NULL,'與','预 豫',NULL,NULL,NULL,'参与',NULL);
DELETE FROM HZMorph WHERE tHZ='乃' AND tPY='nai3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乃','nai3','naix',27,1,NULL,NULL,NULL,NULL,NULL,NULL,'𠄎','迺 廼 仍','弓','汝 尔',NULL,'乃是 乃翁',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','ya4','eat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'乚',NULL,'轧',NULL,'乙乙','古代汉语大词典读ya4');
DELETE FROM HZMorph WHERE tHZ='乙' AND tPY='yi3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','it',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'虚拟广韵读音');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','iut',45,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'甲乙 乙等','粤语读圆唇(通字S18-6)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','ic',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'意','忆',NULL,NULL,'意古音-ks。简体声旁省作乙');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','it',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠃉',NULL,'鳦',NULL,'非凫则乙','乙鸟燕也');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('九','jiu1','cieu',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'鸠 鳩',NULL,'纠',NULL,'九杂天下之川',NULL);
DELETE FROM HZMorph WHERE tHZ='九' AND tPY='jiu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('九','jiu3','cieux',1453,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'玖 久',NULL,'鞠',NULL,'九曲 九死',NULL);
DELETE FROM HZMorph WHERE tHZ='乾' AND tPY='gan1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乾','gan1','con',7,1,'倝','gan4','conh',NULL,NULL,NULL,'乹','干 漧',NULL,'旱',NULL,'乾燥',NULL);
DELETE FROM HZMorph WHERE tHZ='乾' AND tPY='qian2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乾','qian2','gien',1,1,'倝','gan4','conh',NULL,NULL,NULL,'乹',NULL,NULL,NULL,NULL,'乾坤',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='le5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','le5','le',30101,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'完了',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='liao3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','liao3','liaux',654,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'瞭',NULL,NULL,NULL,'已了 了解',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='liao4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','liao4','liauh',19,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'瞭',NULL,NULL,NULL,'了望',NULL);
DELETE FROM HZMorph WHERE tHZ='二' AND tPY='er4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('二','er4','erh',2718,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'弍','贰',NULL,'次',NULL,'二流','据官话吴语日止ri作er(通字S7-8); 次,说文二声,子音七,古snh-');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('于','xu1','xiu',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'吁',NULL,NULL,NULL,'于嗟',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('于','yu1','iu',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'迂',NULL,NULL,NULL,'况于其身',NULL);
DELETE FROM HZMorph WHERE tHZ='于' AND tPY='yu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('于','yu2','yu',3483,1,NULL,NULL,NULL,NULL,NULL,NULL,'亐','於 邘','亏',NULL,NULL,'于是','通字S8表GCC於(影母遇开,与于迂古音异)从于');
DELETE FROM HZMorph WHERE tHZ='亏' AND tPY='kui1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('亏','kui1','kui',71,0,'虧','kui1','kui',1,NULL,NULL,'虧',NULL,NULL,NULL,NULL,'亏欠 幸亏',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('亏','yu2','yu',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'于 亐',NULL,NULL,NULL,'於也(说文)。今作于(康熙)');
DELETE FROM HZMorph WHERE tHZ='人' AND tPY='ren2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ren2','ren',16866,1,NULL,NULL,NULL,NULL,NULL,'ren5',NULL,'仁 夷',NULL,'仁',NULL,'人民',NULL);
DELETE FROM HZMorph WHERE tHZ='人' AND tPY='ren5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ren5','ren',280,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'别人',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ru4','rup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'入',NULL,NULL,NULL,'内(內)声旁,今入作人');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('倝','gan4','conh',NULL,1,'㫃','yan3','yenx',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'日始出,光倝倝也','从旦㫃声(说文)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','ge2','ceac',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'格',NULL,'格',NULL,'昭假无赢','至也');
DELETE FROM HZMorph WHERE tHZ='假' AND tPY='jia3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','jia3','ceax',222,1,'叚','jia3','ceax',NULL,NULL,NULL,NULL,'叚 嘏 瘕 仮',NULL,'雇',NULL,'假借 假如 真假','借,因,大');
DELETE FROM HZMorph WHERE tHZ='假' AND tPY='jia4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','jia4','ceah',44,1,NULL,NULL,NULL,NULL,'jia3',NULL,NULL,NULL,NULL,'暇',NULL,'休假','休沐也');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','jie5','ceah',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'价',NULL,NULL,NULL,'几年假,为拐儿','助词');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','xia2','hea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'遐 瑕',NULL,NULL,NULL,'登假','遠也');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('假','xia4','heah',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'嘉',NULL,NULL,NULL,'假哉皇考','嘉也。汉语大词典读xia4,今读jia3');
DELETE FROM HZMorph WHERE tHZ='儿' AND tPY='er2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','er2','er',581,0,NULL,NULL,NULL,NULL,NULL,NULL,'兒 児',NULL,NULL,'伢',NULL,'儿童',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','ni2','qei',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'兒','𫠜',NULL,'倪',NULL,'儿齿 儿宽（人名）','姓');
DELETE FROM HZMorph WHERE tHZ='儿' AND tPY='r5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','r5','r',3254,0,NULL,NULL,NULL,NULL,NULL,NULL,'兒',NULL,NULL,NULL,NULL,'小孩儿','不成音节词尾-er作-r(通字S7-8)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','ren2','ren',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'人',NULL,NULL,NULL,'兄允从人(说文)。孔子曰:人在下,故诘屈');
DELETE FROM HZMorph WHERE tHZ='兒' AND tPY='er2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('兒','er2','er',6,1,NULL,NULL,NULL,NULL,NULL,NULL,'儿 児',NULL,NULL,'伢',NULL,'兒子',NULL);
DELETE FROM HZMorph WHERE tHZ='兒' AND tPY='ni2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('兒','ni2','qei',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𫠜 齯 倪',NULL,'倪',NULL,'兒寬','姓');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('入','ri4','rup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'日',NULL,NULL,NULL,'骂词,今作日');
DELETE FROM HZMorph WHERE tHZ='入' AND tPY='ru4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('入','ru4','rup',784,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'入口','据官话rip作rup(通字S13-2)');
DELETE FROM HZMorph WHERE tHZ='八' AND tPY='ba1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('八','ba1','bat',1123,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'捌 丷',NULL,NULL,NULL,'八百',NULL);
DELETE FROM HZMorph WHERE tHZ='八' AND tPY='ba2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('八','ba2','bat',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'八岁','在去声字前念阳平(现汉),今非');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','feng1','fung',NULL,NULL,'凡','fan2','fvam',1,NULL,NULL,NULL,'⺇','凡',NULL,NULL,NULL,'简体风凤声旁。说文凡声,今音拟风');
DELETE FROM HZMorph WHERE tHZ='几' AND tPY='ji1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','ji1','ci',216,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'幾 机',NULL,NULL,NULL,'几乎 茶几','古音上声(广韵居履切)');
DELETE FROM HZMorph WHERE tHZ='几' AND tPY='ji3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','ji3','cix',2523,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'幾',NULL,NULL,NULL,'几何',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','shu1','zhu',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠘧',NULL,NULL,NULL,NULL,'殳声旁');
DELETE FROM HZMorph WHERE tHZ='凡' AND tPY='fan2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('凡','fan2','fvam',135,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='刀' AND tPY='dao1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('刀','dao1','dau',284,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'舠 鱽 魛 刁','刂 ⺈',NULL,NULL,'菜刀',NULL);
DELETE FROM HZMorph WHERE tHZ='刁' AND tPY='diao1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('刁','diao1','diau',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'叼',NULL,'刀',NULL,'刁民',NULL);
DELETE FROM HZMorph WHERE tHZ='力' AND tPY='li4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('力','li4','lic',2488,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'力量',NULL);
DELETE FROM HZMorph WHERE tHZ='力' AND tPY='li5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('力','li5','lic',97,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'势力','轻声(现汉)。XDHYPLCD 8548词表第1663条(p.523)');
DELETE FROM HZMorph WHERE tHZ='匐' AND tPY='fu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匐','fu2','fvuc',5,1,'畐','fu2','fvuc',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'匍匐',NULL);
DELETE FROM HZMorph WHERE tHZ='匕' AND tPY='bi3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匕','bi3','bix',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'匕首','从反人(说文)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匕','hua4','xuah',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠤎',NULL,NULL,NULL,NULL,'化声旁');
DELETE FROM HZMorph WHERE tHZ='十' AND tPY='shi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('十','shi2','zhip',4082,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'拾 什',NULL,NULL,NULL,'十分',NULL);
DELETE FROM HZMorph WHERE tHZ='卜' AND tPY='bo5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','bo5','bec',25,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'蔔',NULL,NULL,NULL,'萝卜',NULL);
DELETE FROM HZMorph WHERE tHZ='卜' AND tPY='bu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','bu3','buc',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'⺊',NULL,NULL,NULL,'占卜',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','pu2','buc',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'濮',NULL,NULL,NULL,'卜人',NULL);
DELETE FROM HZMorph WHERE tHZ='厂' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','an1','om',1,0,'广','an1','om',1,NULL,NULL,NULL,'庵 广 菴 盦',NULL,NULL,NULL,NULL,'人名用');
DELETE FROM HZMorph WHERE tHZ='厂' AND tPY='chang3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','chang3','changx',731,0,'廠','chang3','changx',1,NULL,NULL,NULL,'廠 厰',NULL,NULL,NULL,'工厂','工厂方言亦作工场,音异');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','han3','xonx',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'汉语大词典上去皆读han3,义同。音同罕有两读');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','han4','xonh',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'厈','雁','岸',NULL,'石厂','古代汉语大词典读han4。籀文厈从干声。雁略字');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','yan3','qiemx',NULL,NULL,'广','yan3','qiemx',1,NULL,NULL,NULL,NULL,'广',NULL,NULL,NULL,'简体厅厦厨厕形旁');
DELETE FROM HZMorph WHERE tHZ='又' AND tPY='you4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('又','you4','yeuh',4892,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'宥 有 祐',NULL,'有 或',NULL,'又名',NULL);
DELETE FROM HZMorph WHERE tHZ='叚' AND tPY='jia3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('叚','jia3','ceax',3,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'假','下',NULL,NULL,'叚,借也(说文)','通作假(康熙)');
DELETE FROM HZMorph WHERE tHZ='叚' AND tPY='xia2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('叚','xia2','hea',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'瑕',NULL,NULL,NULL,'叚嘉','姓(康熙)');
DELETE FROM HZMorph WHERE tHZ='古' AND tPY='gu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('古','gu3','cux',440,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'沽 怙 诂',NULL,'故',NULL,'古代',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('古','gu4','cuh',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'故 固',NULL,NULL,NULL,'古土',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('古','ku1','ku',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'古成',NULL);
DELETE FROM HZMorph WHERE tHZ='吓' AND tPY='he4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('吓','he4','xaec',1,0,NULL,NULL,NULL,NULL,NULL,NULL,'嚇',NULL,NULL,NULL,NULL,'恐吓',NULL);
DELETE FROM HZMorph WHERE tHZ='吓' AND tPY='xia4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('吓','xia4','xeah',135,0,'下','xia4','heah',NULL,NULL,NULL,'嚇',NULL,NULL,NULL,NULL,'吓唬',NULL);
DELETE FROM HZMorph WHERE tHZ='嘏' AND tPY='gu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('嘏','gu3','cux',3,0,'古','gu3','cux',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'祝嘏','今音从古,两读同贾');
DELETE FROM HZMorph WHERE tHZ='嘏' AND tPY='jia3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('嘏','jia3','ceax',1,1,'叚','jia3','ceax',NULL,NULL,NULL,NULL,NULL,NULL,'夏 遐 閑',NULL,NULL,'大遠也(说文)');
DELETE FROM HZMorph WHERE tHZ='嚇' AND tPY='he4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('嚇','he4','xaec',6,1,'赫','he4','xaec',NULL,NULL,NULL,'吓',NULL,NULL,NULL,NULL,'恐嚇',NULL);
DELETE FROM HZMorph WHERE tHZ='嚇' AND tPY='xia4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('嚇','xia4','xeah',1,1,NULL,NULL,NULL,NULL,NULL,NULL,'吓','唬 赫',NULL,NULL,NULL,'驅嚇',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('土','cha3','tyah',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'土苴(zha3)','通字S2无tyax,改去声,如姹今音');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('土','du4','dhux',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'杜',NULL,NULL,NULL,'桑土',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('土','tu2','tux',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'吐',NULL,NULL,NULL,'土门（族名）','汉语大词典');
DELETE FROM HZMorph WHERE tHZ='土' AND tPY='tu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('土','tu3','tux',858,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'土地',NULL);
DELETE FROM HZMorph WHERE tHZ='士' AND tPY='shi4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('士','shi4','zhix',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'事',NULL,NULL,NULL,'勿士行枚','汉语大词典');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('士','shi4','zrix',516,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'仕 恃',NULL,'仕 事',NULL,'士女 武士','一说牡从士则为会意兼形声(段注)');
DELETE FROM HZMorph WHERE tHZ='士' AND tPY='shi5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('士','shi5','zrix',69,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'护士(43) 烈士(26)','轻声(现汉仅护士)。XDHYPLCD 8548词表第3221,4504条(pp553,578)');
DELETE FROM HZMorph WHERE tHZ='大' AND tPY='da4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('大','da4','dhah',11596,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'夫',NULL,'太 泰 多',NULL,'大小',NULL);
DELETE FROM HZMorph WHERE tHZ='大' AND tPY='dai4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('大','dai4','dhaih',177,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'待 代',NULL,NULL,NULL,'大夫','通字不分咍泰');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('大','tai4','taih',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'太',NULL,NULL,NULL,'大无信也',NULL);
DELETE FROM HZMorph WHERE tHZ='夷' AND tPY='yi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('夷','yi2','yi',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'痍 恞 侇 彝',NULL,'尸 矢 肆',NULL,'夷平',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('寸','cun3','tsunx',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'忖',NULL,NULL,NULL,'寸度',NULL);
DELETE FROM HZMorph WHERE tHZ='寸' AND tPY='cun4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('寸','cun4','tsunh',63,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'忖',NULL,'寸土',NULL);
DELETE FROM HZMorph WHERE tHZ='寸' AND tPY='cun5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('寸','cun5','tsunh',29,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'分寸(15) 尺寸(14)','轻声(现汉)。XDHYPLCD 8548词表第6228,6666条(pp611,620)');
DELETE FROM HZMorph WHERE tHZ='工' AND tPY='gong1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('工','gong1','cung',5185,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'功 攻',NULL,'功 攻 贡',NULL,'工人',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('干','an4','qonh',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'豻',NULL,NULL,NULL,'参七十，干五十','汉语大词典');
DELETE FROM HZMorph WHERE tHZ='干' AND tPY='gan1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('干','gan1','con',482,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'乾 乹 亁 漧 竿 幹',NULL,'扞 闬 竿 旱',NULL,'干戈 干扰 干支 干燥',NULL);
DELETE FROM HZMorph WHERE tHZ='干' AND tPY='gan4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('干','gan4','conh',1464,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'幹 榦','旱','翰',NULL,'干部 能干',NULL);
DELETE FROM HZMorph WHERE tHZ='幹' AND tPY='gan4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幹','gan4','conh',6,1,'倝','gan4','conh',NULL,NULL,NULL,NULL,'干 榦',NULL,'翰',NULL,'才幹',NULL);
DELETE FROM HZMorph WHERE tHZ='幾' AND tPY='ji1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji1','ci',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'几 刉 譏 饑 期',NULL,'近',NULL,'幾乎 庶幾',NULL);
DELETE FROM HZMorph WHERE tHZ='幾' AND tPY='ji3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji3','cix',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'几',NULL,NULL,NULL,'幾何',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji4','gih',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'冀 紀',NULL,NULL,NULL,'年幾',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','qi2','gi',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'頎',NULL,'圻 祈',NULL,'幾然而長',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','qi3','kix',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'豈',NULL,NULL,NULL,NULL,'汉语大词典');
DELETE FROM HZMorph WHERE tHZ='广' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('广','an1','om',1,NULL,'庵','an1','om',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('广','yan3','qiemx',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='庵' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('庵','an1','om',7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='廠' AND tPY='chang3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('廠','chang3','changx',6,1,'敞',NULL,NULL,NULL,NULL,NULL,'厰','厂 敞',NULL,NULL,NULL,'廠衛',NULL);
DELETE FROM HZMorph WHERE tHZ='才' AND tPY='cai2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('才','cai2','dzai',2108,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'纔 材 裁',NULL,'纔',NULL,'才能 刚才',NULL);
DELETE FROM HZMorph WHERE tHZ='才' AND tPY='cai5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('才','cai5','dzai',33,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'秀才','轻声(现汉)。XDHYPLCD 8548词表第4192条(p.572)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('才','zai1','zai',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'哉',NULL,NULL,NULL,NULL,'西周金文哉字皆以才为之(汉语大词典)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('暇','jia3','ceax',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'假',NULL,'夏',NULL,'聊暇日以销忧','大,借,皆假义');
DELETE FROM HZMorph WHERE tHZ='暇' AND tPY='xia2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('暇','xia2','hea',7,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'闲',NULL,'自顾不暇','古音去声,今音从霞');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('暇','xia4','heah',0,1,'叚','jia3','ceax',NULL,NULL,NULL,NULL,'下',NULL,NULL,NULL,NULL,'旧读');
DELETE FROM HZMorph WHERE tHZ='榦' AND tPY='gan4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('榦','gan4','conh',6,1,'倝','gan4','conh',NULL,NULL,NULL,NULL,'幹',NULL,NULL,NULL,'楨榦',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('榦','han2','hon',NULL,NULL,'倝','gan4','conh',NULL,NULL,NULL,NULL,'韓',NULL,NULL,NULL,'夫據榦而窺井底',NULL);
DELETE FROM HZMorph WHERE tHZ='毚' AND tPY='chan2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('毚','chan2','jram',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'讒 纔',NULL,NULL,NULL,'毚兔',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('畐','bi4','bhic',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'通字S24无pic,滂改并');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('畐','fu2','fvuc',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'畗',NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='纔' AND tPY='cai2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('纔','cai2','dzai',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'才',NULL,'才',NULL,'方纔','广韵去声义同,今并入平声');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('纔','shan1','sram',NULL,1,'毚','chan2','jram',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'毚(纔)微','浅也(说文),犹言仅至也(康熙)。今用为才字(段注)');
DELETE FROM HZMorph WHERE tHZ='舁' AND tPY='yu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('舁','yu2','yu',3,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'舆',NULL,'誉 舆 举',NULL,'虎贲舁上殿就坐',NULL);
DELETE FROM HZMorph WHERE tHZ='與' AND tPY='yu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('與','yu2','yu',1,1,'舁','yu2','yu',NULL,NULL,NULL,'与','歟',NULL,'邪',NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='與' AND tPY='yu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('與','yu3','yux',6,1,'与','yu3','yux',NULL,NULL,NULL,'与','舉 予',NULL,'舍 與',NULL,'贈與',NULL);
DELETE FROM HZMorph WHERE tHZ='與' AND tPY='yu4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('與','yu4','yuh',1,1,'与','yu3','yux',NULL,NULL,NULL,'与','預 豫',NULL,NULL,NULL,'參與',NULL);
DELETE FROM HZMorph WHERE tHZ='蔔' AND tPY='bo5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('蔔','bo5','bec',6,1,'匐','fu2','fvuc',NULL,NULL,NULL,NULL,'菔',NULL,NULL,NULL,'蘿蔔',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('虍','hu5','xu',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'虎',NULL,NULL,NULL,'虎文也(说文)');
DELETE FROM HZMorph WHERE tHZ='虧' AND tPY='kui1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('虧','kui1','kui',6,1,'雐','hu1','xu',NULL,NULL,NULL,'亏 虧 𧇾',NULL,NULL,NULL,NULL,'吃虧','从亐雐声。虧或从兮(说文)');
DELETE FROM HZMorph WHERE tHZ='虾' AND tPY='ha2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('虾','ha2','hea',1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='虾' AND tPY='xia1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('虾','xia1','xea',46,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='赫' AND tPY='he4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('赫','he4','xaec',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'嚇',NULL,'赤 赮 瑕 霞 騢 嚇',NULL,'显赫',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('赫','xi4','kiec',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'虩 覤',NULL,'赫蹄','通字S22无xiec,晓改溪');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('赫','xia4','xeah',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'嚇',NULL,NULL,NULL,'反予来赫',NULL);
DELETE FROM HZMorph WHERE tHZ='迺' AND tPY='nai3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('迺','nai3','naix',3,1,NULL,NULL,NULL,NULL,NULL,NULL,'廼 𠧟','乃',NULL,NULL,NULL,NULL,'姓。说文从𠄎省卤(西)声。一说西古音sn-,或说从西乃省声,存疑声部不定');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('雐','hu1','xu',NULL,1,'虍',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'鸟也(说文)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('𫠜','ni2','qei',NULL,0,'兒','ni2','qei',NULL,NULL,NULL,'齯',NULL,NULL,NULL,NULL,'𫠜齿',NULL);
CREATE TRIGGER HZGDefaults after insert on HZGraph when min(new.tSimp, new.tGBFB, new.tTrad, new.tB5FB, new.tJpShin, new.tJISFB) is null begin update HZGraph set tSimp = ifnull(new.tSimp, new.tHanzi), tGBFB = ifnull(new.tGBFB, new.tHanzi), tTrad = ifnull(new.tTrad, new.tHanzi), tB5FB = ifnull(new.tB5FB, new.tHanzi), tJpShin = ifnull(new.tJpShin, new.tHanzi), tJISFB = ifnull(new.tJISFB, new.tHanzi) where tHanzi = new.tHanzi; end;
CREATE TRIGGER HZGParChkIns before insert on HZGraph when new.tParent is not null begin select raise(fail, "non-existent parent") where not exists (select 1 from HZGraph where tHanzi = new.tParent); end;
CREATE TRIGGER HZGParChk before update of tParent on HZGraph when new.tParent is not null begin select raise(fail, "parent loop") where new.tParent = new.tHanzi; select raise(fail, "non-existent parent") where not exists (select 1 from HZGraph where tHanzi = new.tParent); end;
CREATE TRIGGER HZGHzChk before update of tHanzi on HZGraph begin select raise(fail, "parent loop") where new.tParent = new.tHanzi; select raise(fail, "would break parent reference") where exists (select 1 from HZGraph where tParent=old.tHanzi limit 1); end;
CREATE TRIGGER HZGParChkDel before delete on HZGraph begin select raise(fail, "would break parent reference") where exists (select 1 from HZGraph where tParent=old.tHanzi limit 1); end;
CREATE TRIGGER HZMPhChkIns before insert on HZMorph when new.tPhon is not null begin select raise(fail, "non-existent phonetic") where  not exists (select 1 from HZMorph where tHZ = new.tPhon); select raise(fail, "non-existent phonetic pinyin") where  new.tPhPY is not null and not exists (select 1 from HZMorph  where tHZ = new.tPhon and tPY = new.tPhPY);  select raise(fail, "non-existent phonetic MGCR") where  new.tPhPY is not null and new.tPhGC is not null and not exists  (select 1 from HZMorph where tHZ = new.tPhon and   tPY = new.tPhPY and tMGCR = new.tPhGC); end;
CREATE TRIGGER HZMPhChk before update of tPhon, tPhPY, tPhGC on HZMorph when new.tPhon is not null begin select raise(fail, "phonetic loop") where new.tPhon = new.tHZ; select raise(fail, "non-existent phonetic") where  not exists (select 1 from HZMorph where tHZ = new.tPhon); select raise(fail, "non-existent phonetic pinyin") where  new.tPhPY is not null and not exists (select 1 from HZMorph  where tHZ = new.tPhon and tPY = new.tPhPY);  select raise(fail, "non-existent phonetic MGCR") where  new.tPhPY is not null and new.tPhGC is not null and not exists  (select 1 from HZMorph where tHZ = new.tPhon and   tPY = new.tPhPY and tMGCR = new.tPhGC); end;
CREATE TRIGGER HZMHzChk before update of tHZ on HZMorph begin select raise(fail, "protected from updating hanzi"); end;
CREATE TRIGGER HZMPyChk before update of tPY on HZMorph begin select raise(fail, "would break pinyin reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and tPhPY = old.tPY and (tPhGC = old.tMGCR or (tPhGC is null and not exists (select 1 from HZMorph where tHZ = old.tHZ and tPY = old.tPY and tMGCR != old.tMGCR))) limit 1); end;
CREATE TRIGGER HZMMgcrChk before update of tMGCR on HZMorph begin select raise(fail, "would break MGCR reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and tPhPY = old.tPY and tPhGC = old.tMGCR limit 1); end;
CREATE TRIGGER HZMPhChkDel before delete on HZMorph begin select raise(fail, "would break phonetic reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and (tPhPY is null or tPhPY = old.tPY) and (tPhGC is null or tPhGC = old.tMGCR) limit 1); end;
