DROP TRIGGER HZGDefaults;
DROP TRIGGER HZGParChkIns;
DROP TRIGGER HZGParChk;
DROP TRIGGER HZGHzChk;
DROP TRIGGER HZGParChkDel;
DROP TRIGGER HZMPhChkIns;
DROP TRIGGER HZMPhChk;
DROP TRIGGER HZMHzChk;
DROP TRIGGER HZMPyChk;
DROP TRIGGER HZMMgcrChk;
DROP TRIGGER HZMPhChkDel;
UPDATE HZGraph SET tTrad='乃 迺 廼', tJpShin='乃' WHERE tHanzi='乃';
UPDATE HZGraph SET tTrad='了 瞭' WHERE tHanzi='了';
UPDATE HZGraph SET tJpShin='二' WHERE tHanzi='二';
UPDATE HZGraph SET tJpShin='児' WHERE tHanzi='儿';
UPDATE HZGraph SET tJpShin='児' WHERE tHanzi='兒';
UPDATE HZGraph SET tTrad='幾 几', tJpShin='幾 机 几' WHERE tHanzi='几';
UPDATE HZGraph SET tJpShin='刀' WHERE tHanzi='刀';
UPDATE HZGraph SET tJpShin='十' WHERE tHanzi='十';
UPDATE HZGraph SET tTrad='卜 蔔', tJpShin='卜 蔔' WHERE tHanzi='卜';
UPDATE HZGraph SET tTrad='廠 厂', tJpShin='厰 厂' WHERE tHanzi='厂';
INSERT INTO HZGraph(tHanzi,tParent,tSimp,tGBFB,tTrad,tB5FB,tJpShin,tJISFB) VALUES('畐',NULL,'畐','匐','畐','匐','畐','畐');
UPDATE HZGraph SET tSimp='卜', tGBFB='卜', tJpShin='蔔' WHERE tHanzi='蔔';
UPDATE HZGraph SET tSimp='乃 迺', tGBFB='乃', tJpShin='乃 迺' WHERE tHanzi='迺';
UPDATE HZGraph SET tGBFB='倪', tTrad='齯', tB5FB='齯', tJpShin='齯', tJISFB='齯' WHERE tHanzi='𫠜';
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi1','it',32747,1,NULL,NULL,NULL,NULL,NULL,'yi2 yi4','弌','壹',NULL,NULL,NULL,'第一','单用或词尾念阴平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi2','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一半','去声前念阳平');
DELETE FROM HZMorph WHERE tHZ='一' AND tPY='yi4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('一','yi4','it',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'一点','阴平、阳平、上声前念去声');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='ding1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding1','dieng',16,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉 疔 叮 盯',NULL,'打',NULL,'壮丁',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','ding4','diengh',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'钉',NULL,NULL,NULL,'密丁','汉语大词典');
DELETE FROM HZMorph WHERE tHZ='丁' AND tPY='zheng1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('丁','zheng1','draeng',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'丁丁','通字S21无dyaeng,知改庄');
DELETE FROM HZMorph WHERE tHZ='七' AND tPY='qi1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('七','qi1','tsit',950,1,NULL,NULL,NULL,NULL,NULL,'qi2',NULL,'柒 漆',NULL,NULL,NULL,'七夕',NULL);
DELETE FROM HZMorph WHERE tHZ='七' AND tPY='qi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('七','qi2','tsit',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'七月','在去声字前念阳平(现汉),今非');
DELETE FROM HZMorph WHERE tHZ='乃' AND tPY='nai3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乃','nai3','naix',27,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'迺 廼',NULL,NULL,NULL,'乃是',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','ya4','eat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'乚',NULL,'轧',NULL,'乙乙','古代汉语大词典读ya4');
DELETE FROM HZMorph WHERE tHZ='乙' AND tPY='yi3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','it',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'虚拟广韵读音');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi3','iut',45,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'甲乙 乙等','粤语读圆唇(通字S18-6)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','ic',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'意','忆',NULL,NULL,'意古音-ks');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('乙','yi4','it',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠃉',NULL,'鳦',NULL,'非凫则乙','乙鸟燕也');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('九','jiu1','cieu',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'鸠 鳩',NULL,'纠',NULL,'九杂天下之川',NULL);
DELETE FROM HZMorph WHERE tHZ='九' AND tPY='jiu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('九','jiu3','cieux',1453,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'玖 久',NULL,'鞠',NULL,'九死',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='le5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','le5','le',30101,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'完了',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='liao3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','liao3','liaux',654,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'瞭',NULL,NULL,NULL,'已了 了解',NULL);
DELETE FROM HZMorph WHERE tHZ='了' AND tPY='liao4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('了','liao4','liauh',19,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'瞭',NULL,NULL,NULL,'了望',NULL);
DELETE FROM HZMorph WHERE tHZ='二' AND tPY='er4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('二','er4','erh',2718,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'弍','贰',NULL,'次',NULL,'二流','据官话吴语日止ri作er(通字S7-8); 次,说文二声,子音七,古snh-');
DELETE FROM HZMorph WHERE tHZ='人' AND tPY='ren2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ren2','ren',16866,1,NULL,NULL,NULL,NULL,NULL,'ren5',NULL,'仁 夷',NULL,'仁',NULL,'人民',NULL);
DELETE FROM HZMorph WHERE tHZ='人' AND tPY='ren5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ren5','ren',280,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'别人',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('人','ru4','rup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'入',NULL,NULL,NULL,NULL,'内(內)声旁');
DELETE FROM HZMorph WHERE tHZ='儿' AND tPY='er2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','er2','er',581,0,NULL,NULL,NULL,NULL,NULL,NULL,'兒 児',NULL,NULL,'伢',NULL,'儿童',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','ni2','qei',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'兒','𫠜',NULL,'倪',NULL,'儿齿 儿宽（人名）','姓');
DELETE FROM HZMorph WHERE tHZ='儿' AND tPY='r5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','r5','r',3254,0,NULL,NULL,NULL,NULL,NULL,NULL,'兒',NULL,NULL,NULL,NULL,'小孩儿','不成音节词尾-er作-r(通字S7-8)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('儿','ren2','ren',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'人',NULL,NULL,NULL,'兄允从人(说文)。孔子曰:人在下,故诘屈');
DELETE FROM HZMorph WHERE tHZ='兒' AND tPY='er2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('兒','er2','er',6,1,NULL,NULL,NULL,NULL,NULL,NULL,'儿 児',NULL,NULL,'伢',NULL,'兒子',NULL);
DELETE FROM HZMorph WHERE tHZ='兒' AND tPY='ni2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('兒','ni2','qei',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𫠜 齯 倪',NULL,'倪',NULL,'兒寬','姓');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('入','ri4','rup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'骂词,今作日');
DELETE FROM HZMorph WHERE tHZ='入' AND tPY='ru4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('入','ru4','rup',784,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'入口','据官话rip作rup(通字S13-2)');
DELETE FROM HZMorph WHERE tHZ='八' AND tPY='ba1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('八','ba1','bat',1123,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'捌 丷',NULL,NULL,NULL,'八百',NULL);
DELETE FROM HZMorph WHERE tHZ='八' AND tPY='ba2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('八','ba2','bat',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'八岁','在去声字前念阳平(现汉),今非');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','feng1','fung',NULL,NULL,'凡','fan2','fvam',1,NULL,NULL,NULL,'⺇','凡',NULL,NULL,NULL,'简体风凤声旁。说文凡声,今音拟风');
DELETE FROM HZMorph WHERE tHZ='几' AND tPY='ji1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','ji1','ci',216,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'幾 机',NULL,NULL,NULL,'几乎 茶几',NULL);
DELETE FROM HZMorph WHERE tHZ='几' AND tPY='ji3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','ji3','cix',2523,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'幾',NULL,NULL,NULL,'几何',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('几','shu1','zhu',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠘧',NULL,NULL,NULL,NULL,'殳声旁');
DELETE FROM HZMorph WHERE tHZ='凡' AND tPY='fan2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('凡','fan2','fvam',135,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='刀' AND tPY='dao1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('刀','dao1','dau',284,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'舠 鱽 魛 刁','刂 ⺈',NULL,NULL,'菜刀',NULL);
DELETE FROM HZMorph WHERE tHZ='刁' AND tPY='diao1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('刁','diao1','diau',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'叼',NULL,'刀',NULL,'刁民',NULL);
DELETE FROM HZMorph WHERE tHZ='力' AND tPY='li4' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('力','li4','lic',2488,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'力量',NULL);
DELETE FROM HZMorph WHERE tHZ='力' AND tPY='li5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('力','li5','lic',97,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'?');
DELETE FROM HZMorph WHERE tHZ='匐' AND tPY='fu2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匐','fu2','fvuc',5,1,'畐','fu2','fvuc',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'匍匐',NULL);
DELETE FROM HZMorph WHERE tHZ='匕' AND tPY='bi3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匕','bi3','bix',7,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'匕首','从反人(说文)');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('匕','hua4','xuah',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'𠤎',NULL,NULL,NULL,NULL,'化声旁');
DELETE FROM HZMorph WHERE tHZ='十' AND tPY='shi2' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('十','shi2','zhip',4082,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'拾 什',NULL,NULL,NULL,'十分',NULL);
DELETE FROM HZMorph WHERE tHZ='卜' AND tPY='bo5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','bo5','bec',25,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'蔔',NULL,NULL,NULL,'萝卜',NULL);
DELETE FROM HZMorph WHERE tHZ='卜' AND tPY='bu3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','bu3','buc',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'⺊',NULL,NULL,NULL,'占卜',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('卜','pu2','buc',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'濮',NULL,NULL,NULL,'卜人',NULL);
DELETE FROM HZMorph WHERE tHZ='厂' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','an1','om',1,0,'广','an1','om',1,NULL,NULL,NULL,'庵 广 菴 盦',NULL,NULL,NULL,NULL,'人名用');
DELETE FROM HZMorph WHERE tHZ='厂' AND tPY='chang3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','chang3','changx',731,0,'廠','chang3','changx',1,NULL,NULL,NULL,'廠 厰',NULL,NULL,NULL,'工厂','工厂方言亦作工场,音异');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','han3','xonx',0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'汉语大词典上去皆读han3,义同。音同罕有两读');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('厂','han4','xonh',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'厈 雁',NULL,'岸',NULL,'石厂','古代汉语大词典读han4。籀文厈。雁略字');
DELETE FROM HZMorph WHERE tHZ='幾' AND tPY='ji1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji1','ci',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'几 刉 譏 饑 期',NULL,'近',NULL,'幾乎 庶幾',NULL);
DELETE FROM HZMorph WHERE tHZ='幾' AND tPY='ji3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji3','cix',6,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'几',NULL,NULL,NULL,'幾何',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','ji4','gih',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'冀 紀',NULL,NULL,NULL,'年幾',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','qi2','gi',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'頎',NULL,'圻 祈',NULL,'幾然而長',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('幾','qi3','kix',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'豈',NULL,NULL,NULL,NULL,'汉语大词典');
DELETE FROM HZMorph WHERE tHZ='广' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('广','an1','om',1,NULL,'庵','an1','om',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='庵' AND tPY='an1' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('庵','an1','om',7,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='廠' AND tPY='chang3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('廠','chang3','changx',6,1,'敞',NULL,NULL,NULL,NULL,NULL,'厰','厂 敞',NULL,NULL,NULL,'廠衛',NULL);
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('畐','bi4','bhic',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'通字S24无pic,滂改并');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('畐','fu2','fvuc',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'畗',NULL,NULL,NULL,NULL,NULL);
DELETE FROM HZMorph WHERE tHZ='蔔' AND tPY='bo5' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('蔔','bo5','bec',6,1,'匐','fu2','fvuc',NULL,NULL,NULL,NULL,'菔',NULL,NULL,NULL,'蘿蔔',NULL);
DELETE FROM HZMorph WHERE tHZ='迺' AND tPY='nai3' AND tMGCR='';
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('迺','nai3','naix',3,1,'西',NULL,NULL,NULL,NULL,NULL,'廼 𠧟','乃',NULL,NULL,NULL,NULL,'姓。一说西古音sn-');
INSERT INTO HZMorph(tHZ,tPY,tMGCR,nFreq,bInGY,tPhon,tPhPY,tPhGC,bPhSP,tMsPY,tSndh,tVar1,tVar2,tVar3,tCogn,tCoin,tSmpl,tRem) VALUES('𫠜','ni2','qei',NULL,0,'兒','ni2','qei',NULL,NULL,NULL,'齯',NULL,NULL,NULL,NULL,'𫠜齿',NULL);
CREATE TRIGGER HZGDefaults after insert on HZGraph when min(new.tSimp, new.tGBFB, new.tTrad, new.tB5FB, new.tJpShin, new.tJISFB) is null begin update HZGraph set tSimp = ifnull(new.tSimp, new.tHanzi), tGBFB = ifnull(new.tGBFB, new.tHanzi), tTrad = ifnull(new.tTrad, new.tHanzi), tB5FB = ifnull(new.tB5FB, new.tHanzi), tJpShin = ifnull(new.tJpShin, new.tHanzi), tJISFB = ifnull(new.tJISFB, new.tHanzi) where tHanzi = new.tHanzi; end;
CREATE TRIGGER HZGParChkIns before insert on HZGraph when new.tParent is not null begin select raise(fail, "non-existent parent") where not exists (select 1 from HZGraph where tHanzi = new.tParent); end;
CREATE TRIGGER HZGParChk before update of tParent on HZGraph when new.tParent is not null begin select raise(fail, "parent loop") where new.tParent = new.tHanzi; select raise(fail, "non-existent parent") where not exists (select 1 from HZGraph where tHanzi = new.tParent); end;
CREATE TRIGGER HZGHzChk before update of tHanzi on HZGraph begin select raise(fail, "parent loop") where new.tParent = new.tHanzi; select raise(fail, "would break parent reference") where exists (select 1 from HZGraph where tParent=old.tHanzi limit 1); end;
CREATE TRIGGER HZGParChkDel before delete on HZGraph begin select raise(fail, "would break parent reference") where exists (select 1 from HZGraph where tParent=old.tHanzi limit 1); end;
CREATE TRIGGER HZMPhChkIns before insert on HZMorph when new.tPhon is not null begin select raise(fail, "non-existent phonetic") where  not exists (select 1 from HZMorph where tHZ = new.tPhon); select raise(fail, "non-existent phonetic pinyin") where  new.tPhPY is not null and not exists (select 1 from HZMorph  where tHZ = new.tPhon and tPY = new.tPhPY);  select raise(fail, "non-existent phonetic MGCR") where  new.tPhPY is not null and new.tPhGC is not null and not exists  (select 1 from HZMorph where tHZ = new.tPhon and   tPY = new.tPhPY and tMGCR = new.tPhGC); end;
CREATE TRIGGER HZMPhChk before update of tPhon, tPhPY, tPhGC on HZMorph when new.tPhon is not null begin select raise(fail, "phonetic loop") where new.tPhon = new.tHZ; select raise(fail, "non-existent phonetic") where  not exists (select 1 from HZMorph where tHZ = new.tPhon); select raise(fail, "non-existent phonetic pinyin") where  new.tPhPY is not null and not exists (select 1 from HZMorph  where tHZ = new.tPhon and tPY = new.tPhPY);  select raise(fail, "non-existent phonetic MGCR") where  new.tPhPY is not null and new.tPhGC is not null and not exists  (select 1 from HZMorph where tHZ = new.tPhon and   tPY = new.tPhPY and tMGCR = new.tPhGC); end;
CREATE TRIGGER HZMHzChk before update of tHZ on HZMorph begin select raise(fail, "protected from updating hanzi"); end;
CREATE TRIGGER HZMPyChk before update of tPY on HZMorph begin select raise(fail, "would break pinyin reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and tPhPY = old.tPY and (tPhGC = old.tMGCR or (tPhGC is null and not exists (select 1 from HZMorph where tHZ = old.tHZ and tPY = old.tPY and tMGCR != old.tMGCR))) limit 1); end;
CREATE TRIGGER HZMMgcrChk before update of tMGCR on HZMorph begin select raise(fail, "would break MGCR reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and tPhPY = old.tPY and tPhGC = old.tMGCR limit 1); end;
CREATE TRIGGER HZMPhChkDel before delete on HZMorph begin select raise(fail, "would break phonetic reference") where exists (select 1 from HZMorph where tPhon = old.tHZ and (tPhPY is null or tPhPY = old.tPY) and (tPhGC is null or tPhGC = old.tMGCR) limit 1); end;
